import Image from 'next/image'
import TaskkiteShowcase from './_components/TaskkiteShowcase';
import Email from './_components/Email';

const CODEBERG_PAGE = "https://codeberg.org/aidanhammond/";
const TASKKITE_PAGE = "https://taskkite.ahammond.me";

function Projects() {
	const projects = [
		["dotfiles", "My dotfiles"],
		["forum", "Forum project built on Next.js and MongoDB"],
		["sandboxed", "Falling sand simulation in Rust and WGPU"],
		["taskkite", "Taskkite, task management system made with Next.js and MySQL deployed on Digital Ocean with Docker"],
		["personal-site", "This static site generated by Next.js"]];
	return <div id="projects">
		<hgroup>
			<h1><a href={CODEBERG_PAGE}>Checkout</a> my other projects,</h1>
			<p>{"but don't forget about "}<a href={TASKKITE_PAGE}>Taskkite!</a></p>
		</hgroup>
		<ul>{projects.map((project) => <li key={project[0]}><a target="_blank" href={CODEBERG_PAGE + project[0]}>{project[1]}</a></li>)}</ul>
	</div>
}

function Technologies() {
	const technologies: [string, string][] = [
		["nextjs", "https://nextjs.org/"],
		["react", "https://react.dev/"],
		["redux", "https://redux.js.org/"],
		["tailwind_css", "https://tailwindcss.com/"],
		["typescript", "https://www.typescriptlang.org/"],
		["nodejs", "https://nodejs.org/en"],
		["mysql", "https://www.mysql.com/"],
		["rust", "https://www.rust-lang.org/"],
		["wgpu", "https://wgpu.rs/"],
		["neovim", "https://neovim.io/"],
	];

	return <div id="technologies">
		<h1><b>Technologies</b> I enjoy</h1>
		<ImageLinks size={100} links={technologies} base="technologies" />
	</div>
}

function ImageLinks({ links, base, size }: { size: number, base: string, links: [string, string][] }) {
	return <ul>
		{links.map((tech) => <li key={tech[0]}><a target="_blank" href={tech[1]}>
			<Image src={"/" + base + "/" + tech[0] + ".svg"} width={size} height={size} alt={tech[0] + " logo"} /></a></li>)}
	</ul>
}

function Writings() {
	return <></>
}

function Bookmarks() {
	return <></>
}

function Socials() {
	const socials: [string, string][] = [
		["codeberg", CODEBERG_PAGE],
		["linked_in", "https://www.linkedin.com/in/aidan-r-hammond/"]
	];
	return <ImageLinks size={60} links={socials} base="socials" />
}

export default function Home() {
	return <div>
		<header>
			<div>Aidan Hammond</div>
			<nav>
				<a href="#projects">Projects</a>
				<a href="#technologies">Technologies</a>
				<a href="#writings">Writings</a>
				<a href="#bookmarks">Bookmarks</a>
			</nav>
			<a href="#contact">Contact</a>
		</header>
		<div className="taskkite">
			<hgroup>
				<h1>Developing <b>Taskkite</b>,</h1>
				<p>a task management system.</p>
				<a target="_blank" href={TASKKITE_PAGE}>Try it yourself.</a>
			</hgroup>
			<TaskkiteShowcase />
		</div>
		<Projects />
		<Technologies />
		<Writings />
		<Bookmarks />
		<footer id="contact">
			<div>
				<h1>Looking for a developer <b>excited by his craft?</b></h1>
				<p>Shoot me an invite.</p>

			</div>
			<Socials />
			<div>Aidan Hammond <Email email="aidanhammond2003@gmail.com"></Email></div>
		</footer>
	</div>
}
